// Code Generated by Sidekick is for learning and experimentation purposes only.
document.getElementById('contactForm').addEventListener('submit', function(e) {
    e.preventDefault();
    const name = document.getElementById('name').value;
    const email = document.getElementById('email').value;
    const message = document.getElementById('message').value;
    const formMessage = document.getElementById('formMessage');

    // Example of using EmailJS or similar service to send emails
    // Replace 'service_id' and 'template_id' with your actual EmailJS IDs
    emailjs.send('service_id', 'template_id', {
        from_name: name,
        from_email: email,
        message: message
    }).then(response => {
        formMessage.style.color = "lightgreen";
        formMessage.textContent = "Message sent successfully!";
    }).catch(error => {
        formMessage.style.color = "red";
        formMessage.textContent = "Failed to send message.";
    });
});
